# Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

apiVersion: v1
kind: Service
metadata:
  name: vespa
  annotations:
    cloud.google.com/load-balancer-type: "External"
  labels:
    app: vespa
spec:
  # Note: no need to set up load balancer for 19071
  # ToDo: The StatefulSets vespa-feed-container and vespa-query-container need separate load balancers
  type: LoadBalancer
  selector:
    app: vespa
  ports:
  - name: api
    port: 8080
    targetPort: 8080
    protocol: TCP
