# Copyright Verizon Media. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
version: '3.7'
services:
  cfg1:
    image: vespaengine/vespa
    hostname: "cfg1.vespa_net"
    environment:
      - VESPA_CONFIGSERVERS=cfg1.vespa_net,cfg2.vespa_net,cfg3.vespa_net
    ports:
      - target: 19071
        published: 19071
        mode: host
    networks:
      - net
    volumes:
      - data:/opt/vespa/var
      - logs:/opt/vespa/logs

  cfg2:
    image: vespaengine/vespa
    hostname: "cfg2.vespa_net"
    environment:
      - VESPA_CONFIGSERVERS=cfg1.vespa_net,cfg2.vespa_net,cfg3.vespa_net
    networks:
      - net
    volumes:
      - data:/opt/vespa/var
      - logs:/opt/vespa/logs

  cfg3:
    image: vespaengine/vespa
    hostname: "cfg3.vespa_net"
    environment:
      - VESPA_CONFIGSERVERS=cfg1.vespa_net,cfg2.vespa_net,cfg3.vespa_net
    networks:
      - net
    volumes:
      - data:/opt/vespa/var
      - logs:/opt/vespa/logs

  container:
    image: vespaengine/vespa
    command: services
    hostname: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}.vespa_net"
    environment:
      - VESPA_CONFIGSERVERS=cfg1.vespa_net,cfg2.vespa_net,cfg3.vespa_net
    deploy:
       mode: replicated
       replicas: 1
    ports:
      - target: 8080
        published: 8080
        mode: host
    networks:
      - net
    volumes:
      - data:/opt/vespa/var
      - logs:/opt/vespa/logs

  content:
    image: vespaengine/vespa
    command: services
    hostname: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}.vespa_net"
    environment:
      - VESPA_CONFIGSERVERS=cfg1.vespa_net,cfg2.vespa_net,cfg3.vespa_net
    deploy:
       mode: replicated
       replicas: 3
    networks:
      - net
    volumes:
      - data:/opt/vespa/var
      - logs:/opt/vespa/logs

volumes:
  data:
    external: true
    name: '{{.Service.Name}}-{{.Task.Slot}}-data'

  logs:
    external: true
    name: '{{.Service.Name}}-{{.Task.Slot}}-logs'

networks:
  net:
    driver: overlay
    attachable: true
